name: Sync ios-user-guide
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout steps
        uses: actions/checkout@v2.3.4
      - name: Update Docs
        run: npx rdme docs ./docs --key 	rdme_xn8s9hd2ae0c026ac04375da33c4839aecf2288a43c46910ce2745b8f8e95c4b78475f --version 1.2
